[components.yara]

[[components.yara.source-files]]
filename = "yara-4.5.7.tar.gz"
hash = "53dc2fb3eaa3e6a04081a82999e059f05c3bd84e38221c9e2cc56adb16386c901b8665bcf8d655ef745fba6832aacb1faffefe44dd0b71cd6570759ffad34358"
hash-type = "SHA512"
origin = { type = "download", uri = "https://azltempstaginglookaside.blob.core.windows.net/repo/pkgs_modified/yara/yara-4.5.7.tar.gz/sha512/53dc2fb3eaa3e6a04081a82999e059f05c3bd84e38221c9e2cc56adb16386c901b8665bcf8d655ef745fba6832aacb1faffefe44dd0b71cd6570759ffad34358/yara-4.5.7.tar.gz" }
replace-upstream = true
replace-reason = "Strips benign oss-fuzz seed corpora and `tests/data/` PE fixtures from `yara-4.5.4.tar.gz` that match generic malware-scan heuristics. See `modify_source.sh` next to this file for the full strip list and the companion `Makefile.am` edit that drops `test-pe` from `check_PROGRAMS`."
